name: akademi_al_mobile_app
description: AkademiAl

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  rxdart: ^0.24.1
  http: ^0.12.0+1
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  formz: ^0.3.1
  equatable: ^1.2.5
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  dio: 3.0.10
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^3.1.0
  email_validator: ^1.0.5
  flutter_keyboard_visibility: ^3.3.0
  url_launcher: ^5.7.10
  jwt_decoder: ^1.0.3
  json_annotation: ^3.1.1
  flutter_svg: ^0.19.0
  image_picker: ^0.6.7+14
  uuid: 2.2.2
  image_cropper: ^1.3.1
  modal_bottom_sheet: ^1.0.0+1
  collection: ^1.14.13
  expandable: ^4.1.4
  video_player: ^1.0.1
  youtube_player_flutter: ^7.0.0+7
  flutter_downloader: ^1.5.2
  path_provider: ^1.6.24
  flutter_tex: ^3.6.7+10
  native_pdf_view: any
  youtube_player_iframe: 1.1.0
  skeleton_text: ^1.0.0
  flutter_html: ^1.2.0
  open_mail_app: ^0.0.7
  flushbar: ^1.10.4
  connectivity: ^2.0.2
  convex_bottom_bar: ^2.6.0
  cached_network_image: ^2.5.0
  file_picker: ^2.1.5+1
  chewie: ^0.12.2
  flutter_cached_pdfview: ^0.3.5
  badges: ^1.1.6
  mime: ^0.9.7
  flutter_staggered_grid_view: ^0.3.3
  multi_charts: ^0.2.0
  flutter_emoji: 2.0.0
  file_utils: ^0.1.4
  open_file: ^3.0.3
  permission_handler: ^5.0.1+1
  table_calendar: ^2.3.3
  jiffy: ^4.0.0
  package_info: ^0.4.3+4
  ext_storage: ^1.0.3
  flutter_slidable: ^0.6.0
  pull_to_refresh: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.4
  json_serializable: ^3.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/information_1/information_1.png
    - assets/images/information_1_background/information_1_background.png
    - assets/images/information_2_background/information_2_background.png
    - assets/images/information_3_background/information_3_background.png
    - assets/images/information_4_background/information_4_background.png
    - assets/images/information_2/information_2.png
    - assets/images/information_3/information_3.png
    - assets/images/information_4/information_4.png
    - assets/images/registration_1/registration_1.png
    - assets/images/registration_2/registration_2.png
    - assets/images/registration_3/registration_3.png
    - assets/images/registration_4/registration_4.png
    - assets/images/onboarding_1/onboarding_1.png
    - assets/images/splash_screen/splash_screen.png
    - assets/logos/
    - assets/logos/akademi_logo/akademi_logo.png
    - assets/logos/ministry_logo/ministry_logo.png
    - assets/logos/albania_logo/albania_logo.png
    - assets/logos/kosova_logo/kosova_logo.png
    - assets/logos/diaspora_logo/diaspora_logo.png
    - assets/gifs/
    - assets/avatars/
    - assets/images/teacher/teacher.png
    - assets/images/parent/parent_login.png
    - assets/images/classrooms/classrooms.png
    - assets/images/classrooms_medium/classrooms_medium.png
    - assets/images/classrooms_small/classrooms_small.png
    - assets/images/dashboard_image/dashboard_image.png
    - assets/images/empty_classroom/empty_classroom.png
    - assets/images/score_image/score_image.png
    - assets/images/empty_statistics/empty_statistics.png
    - assets/images/empty_downloaded/empty_downloaded.png
    - assets/images/empty_calendar/empty_calendar.png
    - assets/images/empty_notifications/empty_notifications.png
    - assets/images/empty_homework/empty_homework.png

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: RemixIcons
      fonts:
        - asset: assets/icons/RemixIcons.ttf

flutter_intl:
  enabled: true
  main_locale: sq
